Fixes "implement onNewIntent" crash
If you're implementing ActivityEventListener then we need to have
onNewIntent method as well, else the app crashes when
ReactActivity#onNewIntent is called.

I got the solution from react-native-image-picker where people were
having similar issue
https://github.com/marcshilling/react-native-image-picker/commit/146cf6ee56b9e0953e9136e1491e893b41edb672

This is the original error/crash:
java.lang.AbstractMethodError: abstract method "void
com.facebook.react.bridge.ActivityEventListener.onNewIntent(android.content.Intent)"